import org.codehaus.groovy.grails.plugins.metadata.GrailsPlugin
import org.codehaus.groovy.grails.web.pages.GroovyPage
import org.codehaus.groovy.grails.web.taglib.*
import org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException
import org.springframework.web.util.*
import grails.util.GrailsUtil

class gsp_SAR_layoutsmain_gsp extends GroovyPage {
public String getGroovyPageFileName() { "/WEB-INF/grails-app/views/layouts/main.gsp" }
public Object run() {
Writer out = getOut()
Writer expressionOut = getExpressionOut()
registerSitemeshPreprocessMode()
printHtmlPart(0)
createTagBody(1, {->
printHtmlPart(1)
invokeTag('captureMeta','sitemesh',4,['gsp_sm_xmlClosingForEmptyTag':(""),'charset':("utf-8")],-1)
printHtmlPart(1)
invokeTag('captureMeta','sitemesh',5,['gsp_sm_xmlClosingForEmptyTag':(""),'http-equiv':("X-UA-Compatible"),'content':("IE=edge")],-1)
printHtmlPart(1)
invokeTag('captureMeta','sitemesh',6,['gsp_sm_xmlClosingForEmptyTag':(""),'name':("viewport"),'content':("width=device-width, initial-scale=1")],-1)
printHtmlPart(1)
invokeTag('captureMeta','sitemesh',7,['gsp_sm_xmlClosingForEmptyTag':(""),'name':("description"),'content':("")],-1)
printHtmlPart(1)
invokeTag('captureMeta','sitemesh',8,['gsp_sm_xmlClosingForEmptyTag':(""),'name':("author"),'content':("")],-1)
printHtmlPart(2)
createTagBody(2, {->
createClosureForHtmlPart(3, 3)
invokeTag('captureTitle','sitemesh',10,[:],3)
})
invokeTag('wrapTitleTag','sitemesh',10,[:],2)
printHtmlPart(4)
invokeTag('resources','ui',11,['includeJQuery':("true")],-1)
printHtmlPart(4)
invokeTag('layoutHead','g',12,[:],-1)
printHtmlPart(4)
invokeTag('stylesheet','asset',13,['src':("header.css")],-1)
printHtmlPart(4)
invokeTag('stylesheet','asset',14,['src':("bootstrap.min.css")],-1)
printHtmlPart(4)
invokeTag('stylesheet','asset',15,['src':("bootstrap-theme.css")],-1)
printHtmlPart(5)
invokeTag('stylesheet','asset',16,['src':("bootstrap-theme.min.css")],-1)
printHtmlPart(4)
invokeTag('stylesheet','asset',17,['src':("bootstrap.css")],-1)
printHtmlPart(4)
invokeTag('stylesheet','asset',18,['src':("font-awesome.css")],-1)
printHtmlPart(4)
invokeTag('stylesheet','asset',19,['src':("menu.css")],-1)
printHtmlPart(4)
invokeTag('stylesheet','asset',20,['src':("ui.jqgrid.css")],-1)
printHtmlPart(4)
invokeTag('stylesheet','asset',21,['src':("jquery-ui.css")],-1)
printHtmlPart(4)
invokeTag('layoutResources','r',22,[:],-1)
printHtmlPart(6)
})
invokeTag('captureHead','sitemesh',23,[:],1)
printHtmlPart(6)
createTagBody(1, {->
printHtmlPart(7)
invokeTag('img','g',34,['dir':("images"),'file':("logoSarPequena.png"),'width':("40px"),'height':("35px"),'align':("left")],-1)
printHtmlPart(8)
createTagBody(2, {->
printHtmlPart(9)
createClosureForHtmlPart(10, 3)
invokeTag('link','g',41,['controller':("cliente")],3)
printHtmlPart(11)
})
invokeTag('ifAnyGranted','sec',41,['roles':("ROLE_REVENDEDOR")],2)
printHtmlPart(12)
createTagBody(2, {->
printHtmlPart(9)
createClosureForHtmlPart(13, 3)
invokeTag('link','g',42,['controller':("produto")],3)
printHtmlPart(11)
})
invokeTag('ifAnyGranted','sec',42,['roles':("ROLE_REVENDEDOR")],2)
printHtmlPart(12)
createTagBody(2, {->
printHtmlPart(9)
createClosureForHtmlPart(14, 3)
invokeTag('link','g',43,['controller':("venda")],3)
printHtmlPart(11)
})
invokeTag('ifAnyGranted','sec',43,['roles':("ROLE_REVENDEDOR")],2)
printHtmlPart(12)
createTagBody(2, {->
printHtmlPart(15)
createTagBody(3, {->
printHtmlPart(9)
createClosureForHtmlPart(16, 4)
invokeTag('link','g',47,['controller':("grupoRevendedor")],4)
printHtmlPart(11)
})
invokeTag('ifAnyGranted','sec',47,['roles':("ROLE_GERENTE")],3)
printHtmlPart(17)
createTagBody(3, {->
printHtmlPart(9)
createClosureForHtmlPart(18, 4)
invokeTag('link','g',48,['controller':("revendedor")],4)
printHtmlPart(11)
})
invokeTag('ifAnyGranted','sec',48,['roles':("ROLE_GERENTE")],3)
printHtmlPart(19)
createTagBody(3, {->
printHtmlPart(9)
createClosureForHtmlPart(20, 4)
invokeTag('link','g',49,['controller':("campanha")],4)
printHtmlPart(11)
})
invokeTag('ifAnyGranted','sec',49,['roles':("ROLE_GERENTE")],3)
printHtmlPart(21)
createTagBody(3, {->
printHtmlPart(9)
createClosureForHtmlPart(22, 4)
invokeTag('link','g',50,['controller':("pedido")],4)
printHtmlPart(11)
})
invokeTag('ifAnyGranted','sec',50,['roles':("ROLE_GERENTE")],3)
printHtmlPart(23)
createTagBody(3, {->
printHtmlPart(9)
createClosureForHtmlPart(24, 4)
invokeTag('link','g',51,['controller':("usuario"),'action':("enviarMensagem")],4)
printHtmlPart(11)
})
invokeTag('ifAnyGranted','sec',51,['roles':("ROLE_REVENDEDOR")],3)
printHtmlPart(23)
createTagBody(3, {->
printHtmlPart(9)
createClosureForHtmlPart(25, 4)
invokeTag('link','g',52,['controller':("relatorio"),'action':("list")],4)
printHtmlPart(11)
})
invokeTag('ifAnyGranted','sec',52,['roles':("ROLE_REVENDEDOR")],3)
printHtmlPart(26)
})
invokeTag('ifAnyGranted','sec',55,['roles':("ROLE_REVENDEDOR")],2)
printHtmlPart(12)
createTagBody(2, {->
printHtmlPart(27)
createClosureForHtmlPart(28, 3)
invokeTag('link','g',59,['controller':("usuario")],3)
printHtmlPart(29)
createClosureForHtmlPart(30, 3)
invokeTag('link','g',60,['controller':("OAuthID")],3)
printHtmlPart(29)
createClosureForHtmlPart(31, 3)
invokeTag('link','g',61,['controller':("requestmap")],3)
printHtmlPart(29)
createClosureForHtmlPart(32, 3)
invokeTag('link','g',62,['controller':("grupo")],3)
printHtmlPart(29)
createClosureForHtmlPart(33, 3)
invokeTag('link','g',63,['controller':("grupoAtribuicao")],3)
printHtmlPart(29)
createClosureForHtmlPart(34, 3)
invokeTag('link','g',64,['controller':("usuarioGrupo")],3)
printHtmlPart(29)
createClosureForHtmlPart(35, 3)
invokeTag('link','g',65,['controller':("atribuicao")],3)
printHtmlPart(36)
})
invokeTag('ifAnyGranted','sec',68,['roles':("ROLE_ADMIN")],2)
printHtmlPart(37)
invokeTag('layoutBody','g',74,[:],-1)
printHtmlPart(38)
invokeTag('message','g',77,['code':("spinner.alt"),'default':("Loading&hellip;")],-1)
printHtmlPart(39)
invokeTag('layoutResources','r',78,[:],-1)
printHtmlPart(6)
invokeTag('javascript','asset',79,['src':("jquery.min.js")],-1)
printHtmlPart(6)
invokeTag('javascript','asset',80,['src':("jquery-ui-1.9.1.custom.min")],-1)
printHtmlPart(6)
invokeTag('javascript','asset',81,['src':("bootstrap.min.js")],-1)
printHtmlPart(6)
invokeTag('javascript','asset',82,['src':("codemirror.js")],-1)
printHtmlPart(6)
invokeTag('javascript','asset',83,['src':("scripts.min.js")],-1)
printHtmlPart(6)
invokeTag('javascript','asset',84,['src':("grid.locale-pt-br.js")],-1)
printHtmlPart(6)
invokeTag('javascript','asset',85,['src':("jquery.jqGrid.min.js")],-1)
printHtmlPart(6)
invokeTag('javascript','asset',86,['src':("jquery.maskedinput.js")],-1)
printHtmlPart(6)
})
invokeTag('captureBody','sitemesh',87,['class':("body-bottom")],1)
printHtmlPart(40)
}
public static final Map JSP_TAGS = new HashMap()
protected void init() {
	this.jspTags = JSP_TAGS
}
public static final String CONTENT_TYPE = 'text/html;charset=UTF-8'
public static final long LAST_MODIFIED = 1479909975076L
public static final String EXPRESSION_CODEC = 'html'
public static final String STATIC_CODEC = 'none'
public static final String OUT_CODEC = 'html'
public static final String TAGLIB_CODEC = 'none'
}
